name: Default

on:
  push:
  pull_request:
  workflow_call:

jobs:
  clean:
    name: Clean
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ^1.18
          cache: true
        id: go

      - name: Install tools
        run: make install

      - name: Assets
        run: make assets

      - name: Porcelain
        run: |
          make docs
          make porcelain

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ^1.18
          cache: true
        id: go

      - name: Build
        run: make build

      - name: Test
        run: make test

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ^1.18
          cache: true
        id: go

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
